#pragma once
#include <string>
#include <vector>

enum class TokenType {
    CREATE, VAR, ASSIGN, ARROW, CALL, FUNCTION, DO, END, THEN, ELSE,
    CONSOLE_OUTPUT, CONSOLE_ASK, CONSOLE_CHECK,
    CONSOLE_CLEAR, CONSOLE_COLOR, CONSOLE_TITLE, CONSOLE_WAIT,
    CONSOLE_INPUT,
    MATH_CALL, MATH_FLOOR, MATH_CEIL, MATH_SQRT, MATH_POW, MATH_ABS,
    MATH_ROUND, MATH_MIN, MATH_MAX, MATH_RANDOM, MATH_SIN, MATH_COS,
    MATH_TAN, MATH_LOG, MATH_MOD,
    SYSTEM_HARDWARE, APP_OPEN, CALLLOG,
    FETCH, FETCH_POST, FETCH_HEADERS,
    IMPORT, EXPORT, MODULE,
    REPEAT, UNTIL, NIL, REPEAT_FINISH,
    IF, UNLESS, WHY,
    COMPARE, TO, AND,
    FUNCTION_END, FUNCTION_COMPARE,
    TRUE_KW, FALSE_KW,
    STRING_FUNC, STRING_LEN, STRING_UPPER, STRING_LOWER, STRING_TRIM,
    STRING_SPLIT, STRING_JOIN, STRING_CONTAINS, STRING_REPLACE,
    STRING_STARTS, STRING_ENDS, STRING_SUB, STRING_FIND, STRING_REPEAT,
    STRING_REVERSE, STRING_FORMAT,
    TABLE_PUSH, TABLE_POP, TABLE_LEN, TABLE_GET, TABLE_SET,
    TABLE_REMOVE, TABLE_CONTAINS, TABLE_KEYS, TABLE_MERGE, TABLE_SORT,
    TABLE_SLICE, TABLE_MAP, TABLE_FILTER, TABLE_EACH,
    FILE_READ, FILE_WRITE, FILE_APPEND, FILE_EXISTS, FILE_DELETE,
    FILE_LINES, FILE_COPY, FILE_MOVE, FILE_SIZE, FILE_MKDIR,
    TYPE_OF, TYPE_CAST, TYPE_IS,
    OS_ENV, OS_EXIT, OS_TIME, OS_DATE, OS_SLEEP, OS_RUN, OS_CWD,
    OS_PLATFORM, OS_ARGS,
    ERROR_TRY, ERROR_CATCH, ERROR_THROW, ERROR_FINALLY,
    FUNC_DEF, FUNC_RETURN, FUNC_CALL_USER,
    SWITCH_DO, SWITCH_CASE, SWITCH_DEFAULT,
    RANGE_CALL, ENUM_DEF, CONST_DEF,
    PIPE_OP,
    ASSERT_KW, INSPECT_KW, REPEAT_TIMES,
    CONSOLE_PRINT, CONSOLE_PRINTLN,
    WHILE_KW, BREAK_KW, CONTINUE_KW,
    INCR, DECR,
    STRING_INTERP,
    CRYPTO_HASH, CRYPTO_B64ENC, CRYPTO_B64DEC, CRYPTO_HEX,
    JSON_PARSE, JSON_STRINGIFY,
    CLIP_READ, CLIP_WRITE,
    NET_PING, NET_PORT, NET_HOST,
    REGEX_MATCH, REGEX_TEST, REGEX_REPLACE, REGEX_FIND,
    TIME_NOW, TIME_FORMAT, TIME_DIFF, TIME_STAMP,
    PROC_PID, PROC_LIST, PROC_KILL,
    CONSOLE_TABLE, CONSOLE_BELL,
    STRING_PAD_LEFT, STRING_PAD_RIGHT, STRING_COUNT, STRING_WRAP,
    MATH_CLAMP, MATH_LERP, MATH_MAP, MATH_PI, MATH_E,
    FETCH_GET, FETCH_POST_KW,
    IDENTIFIER, STRING, NUMBER, BOOLEAN,
    PLUS, MINUS, STAR, SLASH, PERCENT, CARET,
    EQ, NEQ, LT, GT, LEQ, GEQ,
    AND_OP, OR_OP, NOT_OP,
    LPAREN, RPAREN, LBRACKET, RBRACKET, LBRACE, RBRACE,
    SEMICOLON, COLON, COMMA, DOT, BANG,
    COMMENT, PARAGRAPH,
    OR, NUM_KW,
    GLOBAL, LOCAL_KW,
    NEWLINE, END_OF_FILE,
    UNKNOWN
};

struct Token {
    TokenType type;
    std::string value;
    int line;
    Token(TokenType t, std::string v, int l) : type(t), value(std::move(v)), line(l) {}
};

std::vector<Token> tokenize(const std::string& source);
std::string tokenTypeName(TokenType t);
